#+OPTIONS: author:nil
#+OPTIONS: num:0 timestamp:nil toc:nil html-postamble:nil
#+html_link_home: /index
#+html_link_up: /about
#+BEGIN_COMMENT
So kann style bei bedarf angepasst werden
#+END_COMMENT
#+HTML_HEAD_EXTRA: <style> body { background-color: black; color: lime; font-family: Menlo; }</style>

* archive ~
*** 2024
- 17.07.2024 - Veronika Hargitai Ensemble - Pina Bausch Theater Fokwang Udk, Essen-Werden (Jazz)
- 05.06.2024 - Next Generation - ZKM Karlsruhe
- 04.06.2024 - ZIRKUS 42289 - Visiodrom, Wuppertal (360Grad Video + 1ch Tape)
- 02.02.2024 - Kunstakademie Rundgang - Solo - Kunstakademie Düsseldorf (Live Impro/ Noise)
*** 2023
- 17.11.2023 - Rundlauf - chimaira #1 - Neue Musik Zentrale, Essen
- 25.06.2023 - Folkwang Rundgang - Duo mit Philipp Neumann - Campus Nord Folkwang Udk Essen (Live Impro/ Noise)
- 23.06.2023 - Sound of the multitude, Nik Novak Speaker Skulptur - Solo - Open Air, Mülheim an der Ruhr (Noise)
- 23.06.2023 - Sound of the multitude, Nik Novak Speaker Skulptur - Strategie V - Open Air, Mülheim an der Ruhr (Drone Metal)
- 21.05.2023 - 1140 Minuten - Pauli, Kollewijn, Zimmermann, Weigand, Porst, Beseler, Voerste - Tresor West Dortmund (Performance)
- 10.05.2023 - Lauktuves - Solo - Studium P, Vilnius, Litauen (Noise)
- 05.05.2023 - Lauktuves - Solo - Neue Musik Zentrale, Essen (Noise)
- 04.05.2023 - Folkwang Jazzpreis - Felix Riedel Quartett - Pina Bausch Theater Fokwang Udk, Essen-Werden (Jazz)
- 22.04.2023 - Wittener Tage für Neue Kammermusik - Trio - Voerste, Pauli, Bahr - Saalbau, Witten (Live Impro)   
*** 2022
- 18.12.2022 - GNMR Adventskalender - Christmas with Friends - Trio - Voerste, Pauli, Bahr - Neue Musik Zentrale, Essen (Live Impro)
- 10.12.2022 - S201 & friends 1 - Solo - RueBühne, Essen (Noise)
- 01.12.2022 - GNMR Adventskalender - Beseler, Kollewijn, Porst, Voerste, Weigand, Zimmermann - Neue Musik Zentrale, Essen (Performance)
- 15.07.2022 - destruenten #2 - Visiodrom, Wuppertal (360Grad Video + 2ch Tape)
- 24.06.2022 - Next Generation - verschiebungen #1 - ZKM, Karlsruhe (midi-flügel + Ambisonics tape)
- 14.05.2022 - Lucidity Music Schlafkonzert - Solo - KoFabrik, Bochum (Drone)
- 23.04.2022 - Lucidity Music Schlafkonzert - Solo - St. Gertrud, Köln (Drone)
*** 2021
- 05.12.2021 - Stromspiesser - Solo - Gitterraum, Essen (Noise)
- 30.10.2021 - LIVE!REMIX!NOW! - Folkwang Elektrisch - NOW Festival Philharmonie, Essen (Live Impro)
** theatre
- schluss.aus. - Musik - Regie: Antonie Zschoch - St. Pauli Theater HAmburg 2024
- phädra killing me softly - Musik - Regie: Antonie Zschoch - Schauspielhaus Hamburg 2023
- baby, you can't light my fire - Musik/ Video - Regie: Antonie Zschoch - Hfmt Hamburg 2023
- Die Affäre Rue de Lourcine - Musik/ Video - Regie: Markus Heinzelmann - Theater Bielefeld 2022
