#+Title: Biography/ Artist Statements
#+OPTIONS: author:nil
#+OPTIONS: num:0 timestamp:nil toc:nil html-postamble:nil
#+html_link_home: /index
#+html_link_up: /index
#+BEGIN_COMMENT
So kann style bei bedarf angepasst werden
#+END_COMMENT
#+HTML_HEAD_EXTRA: <style> body { background-color: #1E1E1E; color: whitesmoke; font-family: times;} .timestamp { color: whitesmoke; } </style>
Theo Voerste (* 1996) is a composer, artist, performer, improviser, curator, melancholic, hoarder and wannabe clown based in Essen.
Synthetic sounds and structures, as well as language and the physical and spatial properties of sound, are central elements in Theo's work.
Theo frequently recontextualizes and recombines existing material to create new connections and hyperlinks. Post-irony and humor play an important role in this process.
Theo is convinced that music is a collective experience.

The computer is the main tool for their work.
-----
Theo Voerste (* 1996) ist Komponist*, Künstler*, Performer*, Improviser*, Kurator*, Melancholiker*, Sammler* und möchtegern Clown aus Essen.
Synthetische Klänge und Strukturen, sowie Sprache und die physikalischen und räumlichen Eigenschaften von Klang sind zentrale Elemente in Theos Arbeit. Häufig rekontextualisiert und rekombiniert Theo bereits existierendes Material, um neue Zusammenhänge und Hyperlinks zu erzeugen. Postironie und Humor spielen dabei eine wichtig Rolle.
Theo ist davon überzeugt, dass Musik eine kollektive Erfahrung ist.

Der Computer ist Theos Hauptwerkzeug.
