#+Title: Biography/ Artist Statements
#+OPTIONS: author:nil
#+OPTIONS: num:0 timestamp:nil toc:nil html-postamble:nil
#+html_link_home: /index
#+html_link_up: /about
#+BEGIN_COMMENT
So kann style bei bedarf angepasst werden
#+END_COMMENT
#+HTML_HEAD_EXTRA: <style> body { background-color: black; color: lime; font-family: Menlo; }</style>

* English
** Short
Theo Voerste (*1996)
is a composer and artist in the field of time-based media.
He has been studying electronic composition at the Folkwang University of the Arts since 2020.
In his work, he is interested in extreme music and algorithmic structures.
He often recontextualises (pop-)cultural set pieces, focusing in particular on the extreme forms of musical expression.
** Medium 
** Long
* Deutsch
** kurz
Theo Voerste (*1996)
ist Komponist und freischaffender Künstler im Bereich zeitbasierte Medien.
Seit 2020 studiert er Elektronische Komposition an der Folkwang Universität der Künste.
In seiner Arbeit interessiert er sich für extreme Musik und algorithmische Strukturen.
Häufig rekontextualisiert er (pop-)kulturelle Versatzstücke und rückt dabei insbesondere die Extremformen musikalischer Expression in den Fokus.
** mittel
** lang
